### ISSUE TITLE
App was rejected (using private method className)

### ISSUE THREAD

**Issue by nickbit** [rentzsch/jrswizzle#15]
Our app was rejected because it was using the private method above.
It would be great if you could replace `[self className]` with `NSStringFromClass([self class])` to keep Apple happy.

**Comment by rentzsch** [comment]
Pull Requests welcome.

**Comment by nickbit** [comment]
Thank you for the quick response!
PR added: https://github.com/rentzsch/jrswizzle/pull/16

**Comment by marcuswu0814** [comment]
Should this PR tag a version 1.0.1 for cocoapod update?

**Comment by rentzsch** [comment]
@marcuswu0814 yes please
