### ISSUE TITLE
Can you make this a Cocoa Pod?

### ISSUE THREAD

**Issue by mysteriouspants** [rentzsch/jrswizzle#6]
I have a small tool which depends on this, but I didn't want to fork this just to push it out as a pod without permission.

**Comment by rentzsch** [comment]
I know next to nothing about Cocoa Pods, do they require something like a canonical URL and you're worried about stamping JRSwizzle with your github handle? I could add you as a collaborator to this repo so that you could make you changes directly (ideally in a branch at first if that works).

**Comment by mysteriouspants** [comment]
It's actually as simple as publishing a new tag. I see that the current set of tags are a little stale. From there almost anyone can publish the podspec for you if you like.

**Comment by rentzsch** [comment]
I just pushed the overdue v1.0 tag. Enjoy.

**Comment by mysteriouspants** [comment]
You're now on CocoaPods! https://github.com/CocoaPods/Specs/blob/master/JRSwizzle/1.0/JRSwizzle.podspec

Thanks! If there's something you'd like changed in the podspec, such as your email address or name, let me know!

**Comment by rentzsch** [comment]
Looks good to me, thanks!
