### ISSUE TITLE
Ability to swizzle specifying source and target classes.

### ISSUE THREAD

**Issue by drekka** [rentzsch/jrswizzle#7]
Hi, from your source code it appears that you can only swizzle methods on the current class. This doesn't help my situation where I want to swizzle methods on another class which I don't have the source for. I want to do this in a testing situation so that during a test I can switch off certain functionality. For these particular tests I am unable to mock around this code so swizzling is my only hope.

**Comment by Pasta** [comment]
@drekka  Did you managed to do this?

**Comment by drekka** [comment]
Nuts, sorry. I cannot remember the situation I was working with so I'm not sure what I did to resolve it. I should have added more details to the issue :-(

**Comment by aodhol** [comment]
@drekka I'd be very interested in this functionality also, did you manage to accomplish it? Looking through the JRSwizzle source it makes extensive use of 'self'. It would be great to be able to specify the target..

**Comment by drekka** [comment]
HI guys, Yes I've been able to swizzle in methods no problem. In one set of tests I am swizzling in replacements for NSURLConnection::sendSynchronousRequest:returningResponse:error: so that I can control responses from an external server request. Here is the code

TestUtils.m:

```
static IMP originalImp;

+(void) swizzleNSURLConnectionSendSyncWithImp:(IMP) impl {
if (originalMethod == nil) {
    originalMethod = class_getClassMethod([NSURLConnection class], @selector(sendSynchronousRequest:returningResponse:error:));
    originalImp = method_getImplementation(originalMethod);
    }

    // Swizzle
    method_setImplementation(originalMethod, impl);

}

+(void) restoreNSURLConnectionSendSync {
    if (originalMethod != nil) {
        method_setImplementation(originalMethod, originalImp);
    }
}
```

Then I created a bunch of static methods in my test code

```
+ (NSData *)sendSynchronousRequest:(NSURLRequest *)request
                      returningResponse:(NSURLResponse **)response
                                      error:(NSError **)error;
+ (NSData *)errorFromRequest:(NSURLRequest *)request
              returningResponse:(NSURLResponse **)response
                              error:(NSError **)error;
+ (NSData *)errorFromInvalidReponseWithRequest:(NSURLRequest *)request
                                      returningResponse:(NSURLResponse **)response
                                                      error:(NSError **)error;
```

Then called them like this in tests

```
    Method newMethod = class_getClassMethod([self class], @selector(errorFromRequest:returningResponse:error:));
    [TestUtils swizzleNSURLConnectionSendSyncWithImp:method_getImplementation(newMethod)];
...
    [TestUtils restoreNSURLConnectionSendSync];
```

For these unit tests this worked just fine.
